let shopItemsData = [
    {
        id: "Pasta1",
        name: "Fusilli",
        price: 5,
        desc: "Gedraaide stukjes pasta met spiralen en glad oppervlak, voorgekookt, geolied en gezouten, individueel diepgevroren en niet klevend.",
        img: "/assets-pasta/fusilli.png",
    },
    {
        id: "Pasta2",
        name: "Penne",
        price: 5,
        desc: "Buisvormige pasta, schuin afgesneden, met geribd oppervlak, voorgekookt, geolied en gezouten, diepgevroren en niet klevend.",
        img: "/assets-pasta/penne.png",
    },
    {
        id: "Pasta3",
        name: "Farfalle",
        price: 5,
        desc: "Pasta in vlindervorm met glad oppervlak, voorgekookt, geolied en gezouten, individueel diepgevroren en niet klevend.",
        img: "/assets-pasta/farfalle.png",
    },
    {
        id: "Pasta4",
        name: "Macaroni",
        price: 5,
        desc: "Buisvormige pasta met glad oppervlak, voorgekookt, geolied en gezouten, individueel diepgevroren en niet klevend.",
        img: "/assets-pasta/macaroni.png",
    },
    {
        id: "Pasta5",
        name: "Rigatone",
        price: 5,
        desc: "Buisvormige pasta, recht afgesneden, met geribd oppervlak, voorgekookt, geolied en gezouten, diepgevroren en niet klevend.",
        img: "/assets-pasta/rigatone.png",
    },
    {
        id: "Pasta6",
        name: "Conchiglie",
        price: 5,
        desc: "Pasta in vorm van schelpen, met licht geribd oppervlak, voorgekookt, geolied en gezouten, diepgevroren en niet klevend.",
        img: "/assets-pasta/conchiglie.png",
    },
    {
        id: "Pasta7",
        name: "Cappellini",
        price: 5,
        desc: "Cappellini (dunne spaghetti), voorgekookt, geolied en gezouten, diepgevroren in nestjes van 50 g.",
        img: "/assets-pasta/capellini.png",
    },
    {
        id: "Pasta8",
        name: "Tagliatelli",
        price: 5,
        desc: "Tagliatelli, voorgekookt, geolied en gezouten, diepgevroren in nestjes van 50 g.",
        img: "/assets-pasta/tagliatelli.png",
    },
    {
        id: "Saus1",
        name: "Bolognese",
        price: 4,
        desc: "Eenvoudige pastasaus op basis van tomaten, ui en kippengehakt.",
        img: "/assets-pasta/bolognese.png",
    },
    {
        id: "Saus2",
        name: "Napolitana",
        price: 4,
        desc: "Een zachte en gemixte vegetarische tomatensaus met wortelen, basilicum en olijfolie.",
        img: "/assets-pasta/napolitana.png",
    },
    {
        id: "Saus3",
        name: "Carbonara",
        price: 4,
        desc: "Kant-en-klare typische saus op basis van room, Emmental en gerookte spekblokjes.",
        img: "/assets-pasta/carbonara.png",
    },
    {
        id: "Saus4",
        name: "Scampi Crema",
        price: 4,
        desc: "Lekkere vissaus op basis van schaaldieren, room en witte wijn.",
        img: "/assets-pasta/scampicrema.png",
    },
    {
        id: "Saus5",
        name: "Forestière",
        price: 4,
        desc: "Heerlijke romige saus met gerookte spekblokjes en champignons.",
        img: "/assets-pasta/forestiere.png",
    },
    {
        id: "Saus6",
        name: "Maffioso",
        price: 4,
        desc: "Vegetarische kaassaus met spinazie, rode paprika, ui en een snuifje knoflook.",
        img: "/assets-pasta/maffioso.png",
    },
    {
        id: "Saus7",
        name: "Thai Curry",
        price: 4,
        desc: "Thai Curry-saus met stukjes paprika, een zacht pikante smaak en de typische exotische aroma’s van Thaise sauzen.",
        img: "/assets-pasta/bolognese-halal.png",
    },
    {
        id: "Saus8",
        name: "Pesto",
        price: 4,
        desc: "Pasta in vorm van schelpen, met licht geribd oppervlak, voorgekookt, geolied en gezouten, diepgevroren en niet klevend.",
        img: "/assets-pasta/pesto.png",
    },
    {
        id: "Rijst1",
        name: "Witte Rijst",
        price: 5,
        desc: "Deze witte rijst is afkomstig van gezonde granen die grondig werden gereinigd, voorgekookt, gekoeld en IQF bevroren.",
        img: "/assets-pasta/rijst.png",
    },
    {
        id: "Rijst2",
        name: "Basmati Rijst",
        price: 5,
        desc: "Deze Basmati rijst is afkomstig van gezonde granen die grondig werden gereinigd, voorgekookt, gekoeld en IQF bevroren.",
        img: "/assets-pasta/rijst.png",
    },
];